### ISSUE TITLE
[BUG] Create match.

### ISSUE THREAD

**Issue by MikkelDK** [FlowingSPDG/get5-web-go#129] opened 2020-02-08 12:37 UTC
**Where bugs related**
N/A

**Describe the bug**
Problem with creating match (from released) with the original database with plugin/apistats from splewis

**To Reproduce**
1. Go to 'Create A match'
2. Click on 'Choose Server/Teams/Series Type and map.`
3. Scroll down to 'Create Match'

**Expected behavior**
`JSON Unmarshal error: invalid character 'L' after top-level value` (on console) > (Happened, when you try create match) - and if you are clicking on "Create Match" `Internal ERROR`

**Screenshots**
![](https://pic.lindhost.eu/putty_blxoU6Xybw.png)
![](https://pic.lindhost.eu/chrome_CCb9T5VxNX.png)

**Desktop (please complete the following information):**
 - Server OS: [e.g. Debian 9]
 - Go version: [e.g. 1.13.7]
 - Browser [chrome]
 - Version [80.0.3987.87]

**Comment by FlowingSPDG** [comment] 2020-02-09 00:05
Hi,Perhaps you are using wrong Get5 version(the plugin in game_plugins is not compatible with get5-web-go,So I'll remove it soon #130 )
The problem is that phlex's Get5 has different JSON response for get5_web_available .
Which means Go can't parse it properly so that should be the issue
https://github.com/FlowingSPDG/get5-web-go/blob/54df8ac97a99ecc84c27290b557bbcf9137e43d7/server/src/util/util.go#L122

**Comment by MikkelDK** [comment] 2020-02-09 00:10
Hmmm. I don't understand. I'm using Splewis's plugin. ;/

**Comment by PhlexPlexico** [comment] 2020-02-09 01:47
> Hi,Perhaps you are using wrong Get5 version(the plugin in game_plugins is not compatible with get5-web-go,So I'll remove it soon #130 )
> The problem is that phlex's Get5 has different JSON response for get5_web_available .
> Which means Go can't parse it properly so that should be the issue
> 
> https://github.com/FlowingSPDG/get5-web-go/blob/54df8ac97a99ecc84c27290b557bbcf9137e43d7/server/src/util/util.go#L122

That's odd! I didn't think I ever touched the get5_web_available call. I can look into it sometime this week to ensure compatibility :)

**Comment by FlowingSPDG** [comment] 2020-02-09 03:45
@PhlexPlexico Alright thanks! I'll check those JSON marshaling. and I probably need to add more accurate error logs so I'll work on it :)

**Comment by PhlexPlexico** [comment] 2020-02-10 03:35
@MikkelDK is there a possibility you could run `get5_web_available` and produce the output from both mine, and splewis' apistats plugin? It would really help figuring out what's possibly wrong on my end.

Thanks!

**Comment by MikkelDK** [comment] 2020-02-10 05:44
@PhlexPlexico 

Splewis's apistats output:
```
{
    "available": 1,
    "gamestate": 3,
    "avaliable": 1,
    "plugin_version": "0.7.2-dev"
}
//without created match:
    "available": 1,
    "gamestate": 0,
    "avaliable": 1,
    "plugin_version": "0.7.2-dev"
```
Phlex's apistats output:
```
{"available":1,"gamestate":0,"avaliable":1,"plugin_version":"0.7.2-dev"} //without match created.

{"available":1,"gamestate":3,"avaliable":1,"plugin_version":"0.7.2-dev"} //with match created
```

**Comment by FlowingSPDG** [comment] 2020-02-11 09:52
@MikkelDK Thanks for outputs, I think its exactly same with original🤔
did you check SRCDS(CSGO Server) logs?

**Comment by MikkelDK** [comment] 2020-02-11 15:22
> @MikkelDK Thanks for outputs, I think its exactly same with original🤔
> did you check SRCDS(CSGO Server) logs?

I couldn't find any output logs. Since get5-web works normally. but I getting still same issues with your script. (_I should try to build the git, and see about it will work?_

**Comment by FlowingSPDG** [comment] 2020-02-11 19:31
@MikkelDK I've released v0.1.2 binary,so maybe you can try it
Error logs are better than v0.1.1 but Im not sure if it outputs your error as well,let me know once you try latest version!
https://github.com/FlowingSPDG/get5-web-go/releases/tag/v0.1.2

**Comment by MikkelDK** [comment] 2020-02-11 19:35
> @MikkelDK I've released v0.1.2 binary,so maybe you can try it
> Error logs are better than v0.1.1 but Im not sure if it outputs your error as well,let me know once you try latest version!
> https://github.com/FlowingSPDG/get5-web-go/releases/tag/v0.1.2

I will testing now ASAP! @FlowingSPDG

**Comment by MikkelDK** [comment] 2020-02-11 20:06
@FlowingSPDG

**Update: (This is with Phlex's APIstats. I will check with Splewis's APIstats**
2020/02/11 21:05:46 CreateMatch
2020/02/11 21:05:46 JSON Unmarshal error: invalid character 'L' after top-level value
[GIN] 2020/02/11 - 21:05:46 | 500 | 81.706142ms | POST /api/v1/match/create
Error: Error reading get5_web_avaliable response

**Comment by PhlexPlexico** [comment] 2020-02-11 21:22
Any idea if you could print out the JSON before marshaling it? Maybe we'd be able to see something off about it.

**Comment by MikkelDK** [comment] 2020-02-11 21:48
> Any idea if you could print out the JSON before marshaling it? Maybe we'd be able to see something off about it.

How should I do that @PhlexPlexico =D

_I'm not expert with JSON, so dunno how I can print out - (if it should be possible!)_

**Comment by FlowingSPDG** [comment] 2020-02-12 03:35
This is caused by 'get5_web_availiable' response error
https://github.com/FlowingSPDG/get5-web-go/blob/ad29880dabb3d3d7972ed3f63f32d1df1027a40b/server/src/api/api.go#L564

I'll add log that outputs response body if server failed to unmarshal JSON once Im home!(and build binary for u :D )
https://github.com/FlowingSPDG/get5-web-go/blob/ad29880dabb3d3d7972ed3f63f32d1df1027a40b/server/src/util/util.go#L124

btw can u post game server's entire logs?
The error says "invalid character 'L' after top-level value" so we may find something with 'L' string.

**Comment by MikkelDK** [comment] 2020-02-12 08:44
Little update. @FlowingSPDG 

I did check the live-console. and the (get5-web-go) has contact. and it can typo the command of get5_web_avaliable.

**But I can't find any logs about the 'invalid character 'L' after top-level value'**

I saw this on live-console:
```
L 02/12/2020 - 09:40:25: rcon from "VPSIP:55124": command "get5_web_avaliable"
{
"available": 1,
"gamestate": 0,
"avaliable": 1,
"plugin_version": "0.7.2-dev"
}
L 02/12/2020 - 09:40:25: rcon from "VPSIP:55126": command "get5_web_avaliable"
{
"available": 1,
"gamestate": 0,
"avaliable": 1,
"plugin_version": "0.7.2-dev"
}
```

**Comment by PhlexPlexico** [comment] 2020-02-12 13:51
JSON response is grabbing this as the first line from response:

`L 02/12/2020 - 09:40:25: rcon from "VPSIP:55126": command "get5_web_avaliable"`
which means it's likely to fail. There has to be a way to determine if top-level contains this value, and if it does to strip it, maybe?

**Comment by FlowingSPDG** [comment] 2020-02-12 15:28
@MikkelDK @PhlexPlexico  Okay I figured out problem,when you enable log by  ``log on``, Game server will use different format than get5 expects.
Expected : ``{"available":1,"gamestate":0,"avaliable":1,"plugin_version":"0.7.1"}``
With Log on ``{"available":1,"gamestate":0,"avaliable":1,"plugin_version":"0.7.1"}
L 02/12/2020 - 15:24:18: rcon from "118.241.XXX.XXX:55386": command "get5_web_avaliable"``
So log line (`L 02/12/2020 - 15:24:...`) will break JSON format.

If you can solve this problem by disabling log(`log off`),I'll close this issue and create new issue about this problem.

**Comment by MikkelDK** [comment] 2020-02-12 15:45
Yeps. it works with log off (DEACTIVATE!) @FlowingSPDG 

Weird, why it doesn't work with "log on" =D

**Comment by FlowingSPDG** [comment] 2020-02-12 15:46
@MikkelDK Can u check with new binary release : https://github.com/FlowingSPDG/get5-web-go/releases/tag/v0.1.2-rconfix ?

That Go parses JSON with correct format,but accidentially Go loads rcon's next command log,so it won't be correct JSON Format.

**Comment by MikkelDK** [comment] 2020-02-12 16:06
> @MikkelDK Can u check with new binary release : https://github.com/FlowingSPDG/get5-web-go/releases/tag/v0.1.2-rconfix ?
> 
> That Go parses JSON with correct format,but accidentially Go loads rcon's next command log,so it won't be correct JSON Format.

@FlowingSPDG It will only accept with "log off" and not with "log on" I did already tested! =)

**Comment by FlowingSPDG** [comment] 2020-02-12 16:21
@MikkelDK I mean I supported it with `log on` at https://github.com/FlowingSPDG/get5-web-go/releases/tag/v0.1.2-rconfix , so you can Create match / Register Server with logging on :)

**Comment by FlowingSPDG** [comment] 2020-02-15 00:05
I think its solved. Closing issue.

**Closed by FlowingSPDG** 2020-02-15 00:05 UTC
Labels: API, bug

**Comment by FlowingSPDG** [comment] 2020-02-15 01:07
Mention me and Reopen issue if its not solved!
